//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36241
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOfLife.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameOfLife.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CELL SIZE: .
        /// </summary>
        internal static string CellSizeTitle {
            get {
                return ResourceManager.GetString("CellSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COLUMNS: .
        /// </summary>
        internal static string ColumnCountTitle {
            get {
                return ResourceManager.GetString("ColumnCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ANY OTHER KEY TO CONTINUE.
        /// </summary>
        internal static string ExitCancel {
            get {
                return ResourceManager.GetString("ExitCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS $ TO EXIT.
        /// </summary>
        internal static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        internal static string GenerationEmpty {
            get {
                return ResourceManager.GetString("GenerationEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATION: .
        /// </summary>
        internal static string GenerationTitle {
            get {
                return ResourceManager.GetString("GenerationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ? FOR HELP.
        /// </summary>
        internal static string HelpPrompt {
            get {
                return ResourceManager.GetString("HelpPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFE CHANCE: .
        /// </summary>
        internal static string LifeChanceTitle {
            get {
                return ResourceManager.GetString("LifeChanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max:.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROWS: .
        /// </summary>
        internal static string RowCountTitle {
            get {
                return ResourceManager.GetString("RowCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRESS ANY KEY TO CONTINUE.
        /// </summary>
        internal static string SplashScreen {
            get {
                return ResourceManager.GetString("SplashScreen", resourceCulture);
            }
        }
    }
}
